//! `oauth/*`: the OAuth action route for the five kept providers.
//!
//! The providers that left with their tooling (cursor, kiro, kimi, qoder, xai,
//! github, gemini-cli, antigravity, codebuddy-cn, kimchi, trae, windsurf, zed,
//! xiaomi-mimo) are absent here, so the `start-proxy` / `poll-status` /
//! `manual-code` / `ide-status` actions that existed only for them are gone.
//! What stays is what the kept providers use: `authorize`, `device-code`,
//! `exchange` and `poll`, plus the codex proxy session actions.

use std::collections::HashMap;

use axum::Json;
use axum::extract::{Path, Query, State};
use axum::response::{IntoResponse, Response};
use serde_json::{Map, Value, json};

use crate::error::ApiError;
use crate::services::codex_proxy;
use crate::state::AppState;

/// A `Json` body, or `{}` when the request sent none.
fn body_object(payload: Option<&Value>) -> Map<String, Value> {
    payload
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default()
}

/// `GET /api/oauth/{provider}/{action}`.
pub async fn get(
    State(state): State<AppState>,
    Path((provider, action)): Path<(String, String)>,
    Query(query): Query<HashMap<String, String>>,
) -> Response {
    match action.as_str() {
        "authorize" => {
            let redirect_uri = query
                .get("redirect_uri")
                .cloned()
                .unwrap_or_else(|| "http://localhost:8080/callback".to_string());
            let mut meta = Map::new();
            for (k, v) in &query {
                if k != "redirect_uri" {
                    meta.insert(k.clone(), Value::String(v.clone()));
                }
            }
            match router_sse::services::oauth_flow::generate_auth_data(
                &provider,
                &redirect_uri,
                &meta,
            ) {
                Ok(data) => Json(data.to_json()).into_response(),
                Err(e) => ApiError::internal(e).into_response(),
            }
        }
        "device-code" => {
            match router_sse::services::oauth_flow::request_device_code(&provider, None).await {
                Ok(mut data) => {
                    // `codeVerifier` is always returned; for the kept providers
                    // it is the generic PKCE verifier, generated by the
                    // authorize step the client calls first.
                    if let Value::Object(map) = &mut data {
                        map.insert("codeVerifier".into(), Value::Null);
                    }
                    Json(data).into_response()
                }
                Err(e) => ApiError::bad_request(e).into_response(),
            }
        }
        "start-proxy" => {
            if provider != "codex" {
                return ApiError::bad_request("Proxy only supported for codex").into_response();
            }
            let Some(app_port) = query.get("app_port").and_then(|p| p.parse::<u16>().ok()) else {
                return ApiError::bad_request("Missing app_port").into_response();
            };
            let result = codex_proxy::start_proxy(state, app_port).await;
            let mut server_side = false;
            if result.get("success").and_then(Value::as_bool) == Some(true)
                && let (Some(s), Some(cv), Some(ru)) = (
                    query.get("state"),
                    query.get("code_verifier"),
                    query.get("redirect_uri"),
                )
            {
                server_side = codex_proxy::register_session(s, cv, ru);
            }
            let mut out = result;
            if let Value::Object(map) = &mut out {
                map.insert("serverSide".into(), Value::Bool(server_side));
            }
            Json(out).into_response()
        }
        "poll-status" => {
            let Some(state_key) = query.get("state") else {
                return ApiError::bad_request("Missing state").into_response();
            };
            if provider != "codex" {
                return ApiError::bad_request("Poll only supported for codex").into_response();
            }
            let Some(session) = codex_proxy::session_status(state_key) else {
                return Json(json!({ "status": "unknown" })).into_response();
            };
            let mut payload = json!({
                "status": session.status,
                "codeVerifier": session.code_verifier,
                "redirectUri": session.redirect_uri,
            });
            if let Some(err) = &session.error
                && let Value::Object(map) = &mut payload
            {
                map.insert("error".into(), Value::String(err.clone()));
            }
            if let Some(id) = &session.connection_id
                && let Value::Object(map) = &mut payload
            {
                map.insert("connectionId".into(), Value::String(id.clone()));
            }
            if let Some(email) = &session.email
                && let Value::Object(map) = &mut payload
            {
                map.insert("email".into(), Value::String(email.clone()));
            }
            if session.status == "done" || session.status == "error" {
                codex_proxy::clear_session(state_key);
            }
            Json(payload).into_response()
        }
        "stop-proxy" => {
            if provider != "codex" {
                return ApiError::bad_request("Proxy only supported for codex").into_response();
            }
            codex_proxy::stop_proxy();
            Json(json!({ "success": true })).into_response()
        }
        _ => ApiError::bad_request("Unknown action").into_response(),
    }
}

/// `POST /api/oauth/{provider}/{action}`.
pub async fn post(
    State(state): State<AppState>,
    Path((provider, action)): Path<(String, String)>,
    Query(query): Query<HashMap<String, String>>,
    body: Result<Json<Value>, axum::extract::rejection::JsonRejection>,
) -> Response {
    let Ok(Json(payload)) = body else {
        return ApiError::bad_request("Invalid or empty request body").into_response();
    };
    let body = body_object(Some(&payload));

    match action.as_str() {
        "register-session" => {
            let state_key = query.get("state").cloned().or_else(|| {
                body.get("state")
                    .and_then(Value::as_str)
                    .map(str::to_string)
            });
            let Some(state_key) = state_key else {
                return ApiError::bad_request("Missing state").into_response();
            };
            if provider != "codex" {
                return ApiError::bad_request("register-session only supported for codex")
                    .into_response();
            }
            let ok = codex_proxy::register_session(
                &state_key,
                body.get("codeVerifier")
                    .and_then(Value::as_str)
                    .unwrap_or(""),
                body.get("redirectUri")
                    .and_then(Value::as_str)
                    .unwrap_or(""),
            );
            Json(json!({ "success": ok })).into_response()
        }
        "exchange" => exchange(state, &provider, &body).await,
        "poll" => poll(state, &provider, &body).await,
        _ => ApiError::bad_request("Unknown action").into_response(),
    }
}

/// The `exchange` action, minus the branches whose providers were dropped.
async fn exchange(state: AppState, provider: &str, body: &Map<String, Value>) -> Response {
    let code = body.get("code").and_then(Value::as_str).unwrap_or("");
    let redirect_uri = body
        .get("redirectUri")
        .and_then(Value::as_str)
        .unwrap_or("");
    let code_verifier = body
        .get("codeVerifier")
        .and_then(Value::as_str)
        .unwrap_or("");
    let state_key = body.get("state").and_then(Value::as_str).unwrap_or("");
    let meta = body
        .get("meta")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();

    // A raw JWT pasted in place of a code is an access token, not a grant.
    if code.starts_with("eyJ") && code.contains('.') {
        return import_access_token(state, provider, code).await;
    }

    if code.is_empty() || redirect_uri.is_empty() || code_verifier.is_empty() {
        return ApiError::bad_request("Missing required fields").into_response();
    }

    let tokens = match router_sse::services::oauth_flow::exchange_tokens(
        provider,
        code,
        redirect_uri,
        code_verifier,
        state_key,
        &meta,
    )
    .await
    {
        Ok(t) => t,
        Err(e) => return ApiError::internal(e).into_response(),
    };

    save_and_report(state, provider, "oauth", tokens).await
}

/// The `poll` action for device-code providers.
async fn poll(state: AppState, provider: &str, body: &Map<String, Value>) -> Response {
    let Some(device_code) = body.get("deviceCode").and_then(Value::as_str) else {
        return ApiError::bad_request("Missing device code").into_response();
    };
    let code_verifier = body.get("codeVerifier").and_then(Value::as_str);
    let extra = body.get("extraData");

    // kilocode and codebuddy-intl complete without PKCE; grok-cli likewise.
    let result = match router_sse::services::oauth_flow::poll_for_token(
        provider,
        device_code,
        code_verifier,
        extra,
    )
    .await
    {
        Ok(r) => r,
        Err(e) => return ApiError::bad_request(e).into_response(),
    };

    if result.success {
        let tokens = result.tokens.unwrap_or(Value::Null);
        return save_and_report(state, provider, "oauth", tokens).await;
    }

    Json(json!({
        "success": false,
        "error": result.error,
        "errorDescription": result.error_description,
        "pending": result.pending
            || result.error.as_deref() == Some("authorization_pending")
            || result.error.as_deref() == Some("slow_down"),
    }))
    .into_response()
}

/// The `eyJ…` branch: store the pasted JWT as an access-token connection.
async fn import_access_token(state: AppState, provider: &str, token: &str) -> Response {
    let info = router_sse::services::oauth_flow::extract_codex_account_info(token);
    let direct =
        router_sse::services::oauth_flow::decode_jwt_payload(token).unwrap_or_else(|| json!({}));
    let account_id = info
        .get("chatgptAccountId")
        .filter(|v| !v.is_null())
        .or_else(|| direct.get("account_id"));
    let plan_type = info
        .get("chatgptPlanType")
        .filter(|v| !v.is_null())
        .or_else(|| direct.get("plan_type"));
    let email = info
        .get("email")
        .filter(|v| !v.is_null())
        .or_else(|| direct.get("email"));

    let mut psd = Map::new();
    psd.insert("authMethod".into(), Value::String("access_token".into()));
    if let Some(id) = account_id {
        psd.insert("chatgptAccountId".into(), id.clone());
    }
    if let Some(plan) = plan_type {
        psd.insert("chatgptPlanType".into(), plan.clone());
    }

    let data = json!({
        "provider": provider,
        "authType": "access_token",
        "accessToken": token,
        "email": email.cloned().unwrap_or(Value::Null),
        "providerSpecificData": Value::Object(psd),
        "testStatus": "active",
    });

    match state
        .write(move |tx| router_db::repos::connections::create_provider_connection(tx, &data))
        .await
    {
        Ok(c) => Json(json!({
            "success": true,
            "connection": {
                "id": c.get("id").cloned().unwrap_or(Value::Null),
                "provider": c.get("provider").cloned().unwrap_or(Value::Null),
                "email": c.get("email").cloned().unwrap_or(Value::Null),
                "displayName": c.get("displayName").cloned().unwrap_or(Value::Null),
            }
        }))
        .into_response(),
        Err(e) => ApiError::internal(e.to_string()).into_response(),
    }
}

/// `createProviderConnection({provider, authType, ...tokens, expiresAt,
/// testStatus})` then the `{success, connection:{id, provider, email,
/// displayName}}` shape.
async fn save_and_report(
    state: AppState,
    provider: &str,
    auth_type: &str,
    tokens: Value,
) -> Response {
    let data = codex_proxy::connection_payload(provider, auth_type, tokens);
    match state
        .write(move |tx| router_db::repos::connections::create_provider_connection(tx, &data))
        .await
    {
        Ok(c) => Json(json!({
            "success": true,
            "connection": {
                "id": c.get("id").cloned().unwrap_or(Value::Null),
                "provider": c.get("provider").cloned().unwrap_or(Value::Null),
                "email": c.get("email").cloned().unwrap_or(Value::Null),
                "displayName": c.get("displayName").cloned().unwrap_or(Value::Null),
            }
        }))
        .into_response(),
        Err(e) => ApiError::internal(e.to_string()).into_response(),
    }
}

// ── Import routes ─────────────────────────────────────────────────────────

/// `POST /api/oauth/codex/bulk-import`.
pub async fn codex_bulk_import(
    State(state): State<AppState>,
    body: Result<Json<Value>, axum::extract::rejection::JsonRejection>,
) -> Response {
    let Ok(Json(payload)) = body else {
        return ApiError::bad_request("Invalid JSON body").into_response();
    };
    let Some(accounts) = normalize_accounts(&payload) else {
        return ApiError::bad_request("No accounts provided").into_response();
    };

    let mut results = Vec::new();
    let mut success = 0i64;
    let mut failed = 0i64;

    // SERIAL: createProviderConnection reads max(priority) and reorders inside a
    // transaction; parallel calls would race on the priority assignment.
    for (i, raw) in accounts.iter().enumerate() {
        match build_codex_import_item(raw) {
            Err(e) => {
                failed += 1;
                results.push(json!({ "index": i, "ok": false, "error": e }));
            }
            Ok(data) => match state
                .write(move |tx| {
                    router_db::repos::connections::create_provider_connection(tx, &data)
                })
                .await
            {
                Ok(c) => {
                    success += 1;
                    results.push(json!({
                        "index": i,
                        "ok": true,
                        "id": c.get("id").cloned().unwrap_or(Value::Null),
                    }));
                }
                Err(e) => {
                    failed += 1;
                    results.push(json!({ "index": i, "ok": false, "error": e.to_string() }));
                }
            },
        }
    }

    Json(json!({ "success": success, "failed": failed, "results": results })).into_response()
}

/// `POST /api/oauth/codex/import-token`.
pub async fn codex_import_token(
    State(state): State<AppState>,
    body: Result<Json<Value>, axum::extract::rejection::JsonRejection>,
) -> Response {
    let Ok(Json(payload)) = body else {
        return ApiError::bad_request("Invalid JSON body").into_response();
    };
    let Some(access_token) = payload
        .get("accessToken")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
    else {
        return ApiError::bad_request("Access token is required").into_response();
    };
    let name = payload.get("name").and_then(Value::as_str);

    let mut email = None;
    let mut psd = Map::new();
    psd.insert("authMethod".into(), Value::String("access_token".into()));

    if let Some(jwt) = router_sse::services::oauth_flow::decode_jwt_payload(access_token) {
        let auth = jwt
            .get("https://api.openai.com/auth")
            .cloned()
            .unwrap_or_else(|| json!({}));
        let profile = jwt
            .get("https://api.openai.com/profile")
            .cloned()
            .unwrap_or_else(|| json!({}));
        email = profile
            .get("email")
            .and_then(Value::as_str)
            .or_else(|| jwt.get("email").and_then(Value::as_str))
            .or_else(|| jwt.get("preferred_username").and_then(Value::as_str))
            .map(str::to_string);
        if let Some(id) = auth.get("chatgpt_account_id") {
            psd.insert("chatgptAccountId".into(), id.clone());
        }
        if let Some(plan) = auth.get("chatgpt_plan_type") {
            psd.insert("chatgptPlanType".into(), plan.clone());
        }
        if let Some(exp) = jwt.get("exp") {
            psd.insert("jwtExp".into(), exp.clone());
        }
    }
    if email.is_none() {
        let info = router_sse::services::oauth_flow::extract_codex_account_info(access_token);
        email = info
            .get("email")
            .and_then(Value::as_str)
            .map(str::to_string);
        if let Some(id) = info.get("chatgptAccountId").filter(|v| !v.is_null()) {
            psd.insert("chatgptAccountId".into(), id.clone());
        }
        if let Some(plan) = info.get("chatgptPlanType").filter(|v| !v.is_null()) {
            psd.insert("chatgptPlanType".into(), plan.clone());
        }
    }

    let connection_name = name
        .map(str::to_string)
        .or_else(|| email.clone())
        .unwrap_or_else(|| "ChatGPT Access Token".to_string());
    let workspace = psd.get("chatgptAccountId").cloned().unwrap_or(Value::Null);
    let plan = psd.get("chatgptPlanType").cloned().unwrap_or(Value::Null);

    let data = json!({
        "provider": "codex",
        "authType": "access_token",
        "accessToken": access_token,
        "name": connection_name,
        "email": email.clone().map_or(Value::Null, Value::String),
        "providerSpecificData": Value::Object(psd),
        "testStatus": "active",
    });

    match state
        .write(move |tx| router_db::repos::connections::create_provider_connection(tx, &data))
        .await
    {
        Ok(c) => Json(json!({
            "success": true,
            "connection": {
                "id": c.get("id").cloned().unwrap_or(Value::Null),
                "provider": c.get("provider").cloned().unwrap_or(Value::Null),
                "email": c.get("email").cloned().unwrap_or(Value::Null),
                "name": c.get("name").cloned().unwrap_or(Value::Null),
                "workspace": workspace,
                "plan": plan,
            }
        }))
        .into_response(),
        Err(e) => ApiError::internal(e.to_string()).into_response(),
    }
}

/// `POST /api/oauth/grok-cli/bulk-import`.
pub async fn grok_cli_bulk_import(
    State(state): State<AppState>,
    body: Result<Json<Value>, axum::extract::rejection::JsonRejection>,
) -> Response {
    let Ok(Json(payload)) = body else {
        return ApiError::bad_request("Invalid JSON body").into_response();
    };
    let Some(accounts) = normalize_accounts(&payload) else {
        return ApiError::bad_request("No accounts provided").into_response();
    };

    let mut results = Vec::new();
    let mut success = 0i64;
    let mut failed = 0i64;

    for (i, raw) in accounts.iter().enumerate() {
        match build_grok_import_item(raw) {
            Err(e) => {
                failed += 1;
                results.push(json!({ "index": i, "ok": false, "error": e }));
            }
            Ok(data) => {
                let email = data.get("email").cloned().unwrap_or(Value::Null);
                match state
                    .write(move |tx| {
                        router_db::repos::connections::create_provider_connection(tx, &data)
                    })
                    .await
                {
                    Ok(c) => {
                        success += 1;
                        results.push(json!({
                            "index": i,
                            "ok": true,
                            "id": c.get("id").cloned().unwrap_or(Value::Null),
                            "email": c.get("email").cloned().unwrap_or(email),
                        }));
                    }
                    Err(e) => {
                        failed += 1;
                        results.push(json!({ "index": i, "ok": false, "error": e.to_string() }));
                    }
                }
            }
        }
    }

    Json(json!({
        "total": accounts.len(),
        "success": success,
        "failed": failed,
        "results": results,
    }))
    .into_response()
}

// ── Import helpers ────────────────────────────────────────────────────────

/// `[array] | {accounts:[…]} | {…}` → the account list, else `None`.
fn normalize_accounts(body: &Value) -> Option<Vec<Value>> {
    let accounts = if let Some(arr) = body.as_array() {
        arr.clone()
    } else if let Some(arr) = body.get("accounts").and_then(Value::as_array) {
        arr.clone()
    } else if body.is_object() {
        vec![body.clone()]
    } else {
        return None;
    };
    if accounts.is_empty() {
        None
    } else {
        Some(accounts)
    }
}

/// One codex bulk-import item, or the error message for a bad one.
fn build_codex_import_item(raw: &Value) -> Result<Value, String> {
    let Some(obj) = raw.as_object() else {
        return Err("Item is not an object".into());
    };
    // Server-controlled fields are stripped, never trusted from the import.
    let mut item: Map<String, Value> = obj
        .iter()
        .filter(|(k, _)| {
            !matches!(
                k.as_str(),
                "id" | "provider" | "authType" | "createdAt" | "updatedAt"
            )
        })
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();

    if item.get("accessToken").and_then(Value::as_str).is_none() {
        return Err("Missing accessToken".into());
    }

    let mut psd = item
        .get("providerSpecificData")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let needs_email = item.get("email").map(|v| v.is_null()).unwrap_or(true);
    let needs_account = !psd.contains_key("chatgptAccountId");
    let needs_plan = !psd.contains_key("chatgptPlanType");

    if needs_email || needs_account || needs_plan {
        let id_token = item
            .get("idToken")
            .and_then(Value::as_str)
            .or_else(|| item.get("accessToken").and_then(Value::as_str))
            .unwrap_or("");
        let info = router_sse::services::oauth_flow::extract_codex_account_info(id_token);
        if needs_email && let Some(email) = info.get("email").and_then(Value::as_str) {
            item.insert("email".into(), Value::String(email.to_string()));
        }
        if needs_account && let Some(id) = info.get("chatgptAccountId").filter(|v| !v.is_null()) {
            psd.insert("chatgptAccountId".into(), id.clone());
        }
        if needs_plan && let Some(plan) = info.get("chatgptPlanType").filter(|v| !v.is_null()) {
            psd.insert("chatgptPlanType".into(), plan.clone());
        }
    }
    if !psd.is_empty() {
        item.insert("providerSpecificData".into(), Value::Object(psd));
    }

    if item.get("expiresAt").map(|v| v.is_null()).unwrap_or(true)
        && let Some(secs) = item.get("expiresIn").and_then(Value::as_i64)
        && secs > 0
    {
        item.insert("expiresAt".into(), Value::String(expires_iso(secs)));
    }
    item.entry("testStatus".to_string())
        .or_insert(Value::String("active".into()));
    item.entry("isActive".to_string())
        .or_insert(Value::Bool(true));
    item.entry("lastRefreshAt".to_string())
        .or_insert(Value::String(now_iso()));
    item.insert("provider".into(), Value::String("codex".into()));
    item.insert("authType".into(), Value::String("oauth".into()));
    Ok(Value::Object(item))
}

/// One grok-cli bulk-import item.
fn build_grok_import_item(raw: &Value) -> Result<Value, String> {
    let Some(obj) = raw.as_object() else {
        return Err("Item is not an object".into());
    };
    let pick = |snake: &str, camel: &str| {
        obj.get(snake)
            .or_else(|| obj.get(camel))
            .cloned()
            .unwrap_or(Value::Null)
    };
    let access_token = pick("access_token", "accessToken");
    let Some(access) = access_token.as_str().filter(|s| !s.is_empty()) else {
        return Err("Missing access_token / accessToken".into());
    };
    let refresh_token = pick("refresh_token", "refreshToken");
    let id_token = pick("id_token", "idToken");
    let mut email = obj.get("email").cloned().unwrap_or(Value::Null);

    if email.is_null() || email.as_str().is_none_or(str::is_empty) {
        let derived = id_token
            .as_str()
            .and_then(router_sse::services::oauth_flow::decode_xai_id_token_email)
            .or_else(|| router_sse::services::oauth_flow::extract_email_from_access_token(access));
        email = derived.map_or(Value::Null, Value::String);
    }

    let mut expires_at = pick("expires_at", "expiresAt");
    if expires_at.is_null()
        && let Some(secs) = pick("expires_in", "expiresIn").as_i64()
        && secs > 0
    {
        expires_at = Value::String(expires_iso(secs));
    }

    let mut psd = Map::new();
    psd.insert("authMethod".into(), Value::String("device_code".into()));
    if !id_token.is_null() {
        psd.insert("idToken".into(), id_token.clone());
    }
    if let Some(e) = email.as_str().filter(|s| !s.is_empty()) {
        psd.insert("email".into(), Value::String(e.to_string()));
    }
    if let Some(extra) = obj.get("providerSpecificData").and_then(Value::as_object) {
        for (k, v) in extra {
            psd.insert(k.clone(), v.clone());
        }
    }

    let display = obj
        .get("displayName")
        .or_else(|| obj.get("name"))
        .cloned()
        .unwrap_or(Value::Null);

    Ok(json!({
        "provider": "grok-cli",
        "authType": "oauth",
        "accessToken": access,
        "refreshToken": refresh_token,
        "expiresAt": expires_at,
        "email": email,
        "displayName": display,
        "providerSpecificData": Value::Object(psd),
        "testStatus": "active",
    }))
}

fn now_iso() -> String {
    router_db::time::now_iso()
}

fn expires_iso(secs: i64) -> String {
    chrono::DateTime::from_timestamp_millis(chrono::Utc::now().timestamp_millis() + secs * 1000)
        .map(|d| d.to_rfc3339_opts(chrono::SecondsFormat::Millis, true))
        .unwrap_or_else(now_iso)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_accounts_accepts_all_three_shapes() {
        assert_eq!(normalize_accounts(&json!([{ "a": 1 }])).unwrap().len(), 1);
        assert_eq!(
            normalize_accounts(&json!({ "accounts": [{ "a": 1 }, { "b": 2 }] }))
                .unwrap()
                .len(),
            2
        );
        assert_eq!(normalize_accounts(&json!({ "a": 1 })).unwrap().len(), 1);
        assert!(normalize_accounts(&json!([])).is_none());
        assert!(normalize_accounts(&json!("x")).is_none());
    }

    #[test]
    fn codex_item_strips_server_fields_and_requires_a_token() {
        let item = build_codex_import_item(&json!({
            "id": "server",
            "provider": "server",
            "authType": "server",
            "createdAt": "x",
            "updatedAt": "y",
            "accessToken": "tok",
        }))
        .unwrap();
        assert!(item.get("id").is_none());
        assert_eq!(item.get("provider").and_then(Value::as_str), Some("codex"));
        assert_eq!(item.get("authType").and_then(Value::as_str), Some("oauth"));
        assert_eq!(
            item.get("testStatus").and_then(Value::as_str),
            Some("active")
        );
        assert!(build_codex_import_item(&json!({})).is_err());
        assert!(build_codex_import_item(&json!([1])).is_err());
    }

    #[test]
    fn grok_item_reads_snake_and_camel_case() {
        let item = build_grok_import_item(&json!({
            "access_token": "a",
            "refresh_token": "r",
            "expires_in": 60,
        }))
        .unwrap();
        assert_eq!(item.get("accessToken").and_then(Value::as_str), Some("a"));
        assert!(item.get("expiresAt").and_then(Value::as_str).is_some());
        assert_eq!(
            item.get("providerSpecificData")
                .and_then(|p| p.get("authMethod"))
                .and_then(Value::as_str),
            Some("device_code")
        );
        assert!(build_grok_import_item(&json!({ "accessToken": "" })).is_err());
    }
}
